[project]
name = "agent"
version = "0.1.0"
description = "Agent project"
readme = "README.md"
requires-python = "==3.11.*"

dependencies = [
    "langchain>=1.2.11",
    "langsmith>=0.7.16",

    "langgraph>=1.1.0",
    "langgraph-prebuilt>=1.0.8",
    "langgraph-sdk>=0.4.0",
    "langgraph-api>=0.9.0",

    "langgraph-checkpoint-postgres==3.1.0",
    "langgraph-checkpoint-sqlite==3.0.3",

    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.11",
    "langchain-ollama>=1.0.1",
    "langchain-tavily>=0.2.17",
    "langchain-mcp-adapters>=0.2.2",

    "deepagents>=0.5.0",

    "watchdog==6.0.0",
    "pdfplumber==0.11.9",
    "pymupdf>=1.26.0",

    "openbb==4.7.1",
    "openbb-mcp-server==1.4.0",

    "textual==8.2.7",
    "apscheduler==3.11.2",
    "aiorwlock==1.5.1",
]