services:
  huggingface:
    image: guojingneo/agi-fastapi-hf:66bcdad-dev
    container_name: huggingface
    volumes:
      - /data/agi:/agi/cache
      - /data/model:/agi/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 8005:8005
    environment:
      - 'BASE_URL=http://localhost:8000'
      - 'MODEL_PATH=/agi/models'
      - 'CACHE_DIR=/agi/cache'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - agi-net
      
  whisper:
    image: guojingneo/agi-fastapi-whisper:66bcdad-dev
    container_name: whisper
    volumes:
      - /data/agi:/agi/cache
      - /data/model:/agi/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 8003:8003
    environment:
      - 'BASE_URL=http://localhost:8000'
      - 'MODEL_PATH=/agi/models'
      - 'CACHE_DIR=/agi/cache'
      - 'AGI_DEBUG=True'
      - 'COMPUTE_TYPE=int8'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - agi-net

  image_gen:
    # image: guojingneo/agi-fastapi-image:66bcdad-dev
    image: guojingneo/agi-fastapi-image-3.5:70c72d5-dev
    container_name: image_gen
    volumes:
      - /data/agi:/agi/cache
      - /data/model:/agi/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 8001:8001
    environment:
      - 'TEXT_TO_IMAGE_MODEL_PATH=/agi/models/stable-diffusion-3.5-medium'
      - 'BASE_URL=http://localhost:8000'
      - 'MODEL_PATH=/agi/models'
      - 'CACHE_DIR=/agi/cache'
      - 'AGI_DEBUG=True'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - agi-net
  
  tts:
    image: guojingneo/agi-fastapi-tts:66bcdad-dev
    container_name: tts
    volumes:
      - /data/agi:/agi/cache
      - /data/model:/agi/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 8002:8002
    environment:
      - 'BASE_URL=http://localhost:8000'
      - 'MODEL_PATH=/agi/models'
      - 'CACHE_DIR=/agi/cache'
      - 'AGI_DEBUG=True'
      - 'NVIDIA_VISIBLE_DEVICES=0'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - agi-net
    
  agi:
    image: guojingneo/agi-fastapi-app:66bcdad-dev
    container_name: agi
    volumes:
      - /data/agi:/agi/cache
      - /data/model:/agi/models
    ports:
      - 8000:8000
    depends_on:
      - tts
      - image_gen
      - whisper
      - huggingface
    environment:
      - 'LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/conda/lib/python3.11/site-packages/nvidia/cudnn/lib'
      - 'BASE_URL=http://localhost:8000'
      - 'MODEL_PATH=/agi/models'
      - 'CACHE_DIR=/agi/cache'
      - 'OLLAMA_API_BASE_URL=http://host.docker.internal:11434'
      - 'OLLAMA_DEFAULT_MODE=qwen3:14b'
      - 'OPENAI_API_KEY=xxx'
      - 'AGI_DEBUG=True'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - agi-net

  open-webui:
    image: ghcr.io/neoguojing/open-webui:main-cuda
    container_name: open-webui
    volumes:
      - /data/webui:/app/backend/data
      - ${HOME}/.cache:/root/.cache
    depends_on:
      - agi
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
      - 'AGI_BASE_URL=http://agi:8000/v1'
      - 'AGI_API_KEY=123'

    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - agi-net

networks:
  agi-net:
    driver: bridge
