services:
  agi:
    image: guojingneo/agi-fastapi-app:b46e693-main
    container_name: agi
    volumes:
      - /data/agi:/agi/cache
      - /data/model:/agi/models
    ports:
      - 8000:8000
    environment:
      - 'BASE_URL=http://localhost:8000'
      - 'MODEL_PATH=/agi/models'
      - 'OLLAMA_API_BASE_URL=http://host.docker.internal:11434'
      - 'OLLAMA_DEFAULT_MODE=qwen2.5:14b'
      - 'OPENAI_API_KEY=xxx'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
