services:
  agi:
    image: guojingneo/agi-fastapi-app:b46e693-main
    container_name: agi
    volumes:
      - /data/agi:/agi/cache
      - /data/model:/agi/models
    ports:
      - 8000:8000
    environment:
      - 'BASE_URL=http://localhost:8000'
      - 'MODEL_PATH=/agi/models'
      - 'OLLAMA_API_BASE_URL=http://host.docker.internal:11434'
      - 'OLLAMA_DEFAULT_MODE=qwen3:14b'
      - 'OPENAI_API_KEY=xxx'
      - 'AGI_DEBUG=True'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  open-webui:
    image: ghcr.io/neoguojing/open-webui:main-cuda
    container_name: open-webui
    volumes:
      - /data/webui:/app/backend/data
    depends_on:
      - agi
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
      - 'AGI_BASE_URL=http://agi:8000/v1'
      - 'AGI_API_KEY=123'

    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
