name: "text2image"
backend: "python"

max_batch_size: 4

input [
  {
    name: "PROMPT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "NEG_PROMPT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "MODEL"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "IMAGE"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]

dynamic_batching {
  preferred_batch_size: [1, 2, 4]
  max_queue_delay_microseconds: 20000
}